"""initial schema

Revision ID: b3535b18c356
Revises: 
Create Date: 2026-01-22 14:55:18.162347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3535b18c356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('img_sequence', sa.JSON(), nullable=False),
    sa.Column('next_pair', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('image_a', sa.String(), nullable=False),
    sa.Column('image_b', sa.String(), nullable=False),
    sa.Column('winner_image', sa.String(), nullable=False),
    sa.Column('winner_position', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'image_a', 'image_b', name='uq_session_imagepair')
    )
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_session_id'))

    op.drop_table('evaluation')
    op.drop_table('user_session')
    # ### end Alembic commands ###
